#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

# raspi-gpio
. /usr/share/initramfs-tools/hook-functions #provides copy_exec
rm -f ${DESTDIR}/bin/raspi-gpio                         #copy_exec won't overwrite an existing file
copy_exec /usr/bin/raspi-gpio /bin/raspi-gpio #Takes location in filesystem and location in initramfs as arguments
